apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: myapp
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/logilearn?schema=public"
  JWT_SECRET: "supersecret123"
  GROQ_API_KEY: "masukkan_api_key_anda_disini"
