apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-monitoring
  namespace: argocd
spec:
  project: myapp-project
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 11.4.0
    helm:
      values: |
        service:
          type: NodePort
          nodePort: 30030
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            labelValue: "1"
            searchNamespace: ALL
          datasources:
            enabled: true
            label: grafana_datasource
            labelValue: "1"
            searchNamespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
